name: frontend
version: 0.0.1
author: penlook
description: Penlook Frontend Application
environment:
    sdk: '>=1.0.0 <2.0.0'
dependencies:
    shadow_dom: any
    angular: "1.1.0"
    web_components: ">=0.10.0 <0.11.0"
    browser: ">=0.10.0+2 <0.11.0"
dev_dependencies:
    unittest: any
transformers:
- angular
